//Expense Types
export const GET_EXPENSES = "GET_EXPENSES";
export const ADD_EXPENSE = "ADD_EXPENSE";
export const DELETE_EXPENSE = "DELETE_EXPENSE";
export const EXPENSES_LOADING = "EXPENSES_LOADING";
export const SEARCH_EXPENSES = "SEARCH_EXPENSES";
export const EDIT_EXPENSE = "EDIT_EXPENSE";
